version: '3.8'

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090

  alertmanager:
    image: prom/alertmanager
    volumes:
      - ./alertmanager:/etc/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    ports:
      - 9093:9093

  node-exporter:
    image: prom/node-exporter
    ports:
      - 9100:9100

  nginx:
    image: nginx
    ports:
      - 80:80

  webhook:
    build: ./webhook
    volumes:
      - ./ansible:/ansible
    ports:
      - 5001:5001
